#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 25 08:32:34 2019

@author: valerian
"""
import requests
import json

access_token = "9gwo4VlghXj0LTR3Ea1ExWavp0wMvasfzNREDnL7Hmv2G9HUjUNOFXoK06inBUa7" #choice[0]
url = "https://www.openhumans.org/api/direct-sharing/project/members/?access_token="
url_data = url + str(access_token)
try:
    r = requests.get(url_data)
    r.raise_for_status()
except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
    print("Connection with Open Human is Down")
except requests.exceptions.HTTPError:
    print("Connection with Open Human fail")
else:
    print("Connected to open human")  # Proceed to do stuff with `r`

Data = json.loads(r.text)


import datetime
now = datetime.datetime.now()
y = now.year
m = now.month
n = 1
for users in Data['results']:
    for x in range(0, len(users['data'])):
        if users['data'][x]['basename'] == '2019-7_Nobism.pdf':
            url = (users['data'][x]['download_url'])
            print("======================")

            response = requests.get(url)
            path = '../../Doc/Public_pdf/'
            file = str(y) + "_" + str(m) + "_nobism_" + str(n) + ".pdf"
            final = path + file
            with open(final, 'wb') as f:
                f.write(response.content)
                n += 1
        break